src/Entity/FailedJob.php
<?php 

namespace App\Entity;

use Symfony\Component\Messenger\Envelope;
use Symfony\Component\Messenger\Stamp\ErrorDetailsStamp;
use Symfony\Component\Messenger\Stamp\TransportMessageIdStamp;

class FailedJob 
{
    public function __construct(private Envelope $envelope)
    {
        
    }

    public function getMessage(): object
    {
        return $this->envelope->getMessage();
    }

    public function getId(): string 
    {
        /** @var TransportMessageIdStamp[] $stamps */
        $stamps = $this->envelope->all(TransportMessageIdStamp::class);
        return end($stamps)->getId();
    }

    public function getTitle(): string
    {
        return get_class($this->envelope->getMessage());
    }

    public function getTrace(): string
    {
        /** @var RedeliveryStamp[] $stamps */
        $stamps = $this->envelope->all(ErrorDetailsStamp::class);
        return $stamps[0]->getFlattenException()->getTraceAsString();
    }
}

src/Entity/User.php
<?php

namespace App\Entity;

use App\Repository\UserRepository;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: UserRepository::class)]
#[ORM\Table(name: '`user`')]
class User
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column(type: 'integer')]
    private $id;

    #[ORM\Column(type: 'string', length: 255)]
    private $email;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }
}

src/Form/NotifyUserFormType.php
<?php

namespace App\Form;

use App\Entity\User;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
use Symfony\Component\Form\Extension\Core\Type\CollectionType;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class NotifyUserFormType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('user', EntityType::class, [
                'class' => User::class,
                'choice_label' => 'email'
            ])
            ->add('submit', SubmitType::class, ['label' => 'Notifier'])
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            // Configure your form options here
        ]);
    }
}

src/Controller/PageController.php
<?php

namespace App\Controller;

use App\Form\NotifyUserFormType;
use App\Repository\FailedJobRepository;
use App\Service\AsyncMethodService;
use App\Service\HtmlSanitizerService;
use App\Service\UserNotifierService;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Messenger\MessageBusInterface;
use Symfony\Component\Routing\Annotation\Route;

class PageController extends AbstractController
{
    #[Route('/', name: 'home')]
    public function index(
        Request $request, 
        AsyncMethodService $asyncMethodService,
        FailedJobRepository $failedJobRepository
    ): Response
    {
        $form = $this->createForm(NotifyUserFormType::class, []);
        $form->handleRequest($request);
        if ($form->isSubmitted() && $form->isValid()) {
            $data = $form->getData();
            $asyncMethodService->async(UserNotifierService::class, 'notify', [$data['user']->getId()]);
            $this->addFlash('success', 'La notification a bien été envoyée.');
            return $this->redirectToRoute('home');
        }

        return $this->render('page/index.html.twig', [
            'form' => $form->createView(),
            'jobs' => $failedJobRepository->findAll()
        ]);
    }

    #[Route('/delete/{id}', name: 'job_delete', methods: ["DELETE"])]
    public function delete(int $id, FailedJobRepository $failedJobRepository): Response
    {
        $failedJobRepository->reject($id);
        $this->addFlash('success', 'La tâche a bien été supprimée.');
        return $this->redirectToRoute('home');
    }

    #[Route('/retry/{id}', name: 'job_retry', methods: ["POST"])]
    public function retry(int $id, FailedJobRepository $failedJobRepository, MessageBusInterface $messageBus): Response
    {
        $message = $failedJobRepository->find($id)->getMessage();
        $messageBus->dispatch($message);
        $failedJobRepository->reject($id);
        $this->addFlash('success', 'La tâche a bien été relancée.');
        return $this->redirectToRoute('home');
    }

    #[Route('/sanitize', name: 'test_sanitize')]
    public function testSanitize(
        HtmlSanitizerService $htmlSanitizerService
    )
    {
        $html = $this->renderView('page/sanitize.html.twig');   
        return new Response($htmlSanitizerService->sanitize($html));
    }
}

templates/base.html.twig
<!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8">
        <title>{% block title %}Welcome!{% endblock %}</title>
        <link rel="icon" href="data:image/svg+xml,<svg xmlns=%22http://www.w3.org/2000/svg%22 viewBox=%220 0 128 128%22><text y=%221.2em%22 font-size=%2296%22>⚫️</text></svg>">
        {# Run `composer require symfony/webpack-encore-bundle` to start using Symfony UX #}
        {% block stylesheets %}
            {{ encore_entry_link_tags('app') }}
        {% endblock %}

        {% block javascripts %}
            {{ encore_entry_script_tags('app') }}
        {% endblock %}
    </head>
    <body>
        <div class="container">
            {% block body %}{% endblock %}
        </div>       
    </body>
</html>

templates/page/index.html.twig
{% form_theme form 'bootstrap_5_layout.html.twig' %}
{% extends 'base.html.twig' %}

{% block title %}Symfony Messenger{% endblock %}

{% block body %}    
    {% for label, messages in app.flashes %}
        {% for message in messages %}
            <div class="alert alert-{{ label }}">
                {{ message }}
            </div>
        {% endfor %}
    {% endfor %}

    {{ form(form) }}

    <h3>Tâches échouées</h3>

    <ul>
        {% for job in jobs %}
            <li>
                <h4>{{ job.title }}</h4>

                <pre>
                    {{ job.trace }}
                </pre>

                <form action="{{ path('job_delete', {id: job.id}) }}" method="POST">
                    <input type="hidden" name="_method" value="DELETE">
                    <button class="btn btn-danger">Supprimer</button>
                </form>

                <form action="{{ path('job_retry', {id: job.id}) }}" method="POST">
                    <button class="btn btn-secondary">Relancer</button>
                </form>
            </li>
        {% endfor %}
    </ul>
    
{% endblock %}

templates/page/sanitize.html.twig
{% extends 'base.html.twig' %}

{% block title %}Html Sanitizer{% endblock %}

{% block body %}    
    <div>Div test</div>

    <p>P test</p>
    
{% endblock %}